export const ALL_PROFILE_REQUEST = "ALL_PROFILE_REQUEST";
export const ALL_PROFILE_SUCCESS = "ALL_PROFILE_SUCCESS";
export const ALL_PROFILE_FAIL = "ALL_PROFILE_FAIL";

export const PROFILE_DETAILS_REQUEST = "PROFILE_DETAILS_REQUEST";
export const PROFILE_DETAILS_SUCCESS = "PROFILE_DETAILS_SUCCESS";
export const PROFILE_DETAILS_FAIL = "PROFILE_DETAILS_FAIL";

export const NEW_PROFILE_REQUEST = "NEW_PROFILE_REQUEST";
export const NEW_PROFILE_SUCCESS = "NEW_PROFILE_SUCCESS";
export const NEW_PROFILE_RESET = "NEW_PROFILE_RESET";
export const NEW_PROFILE_FAIL = "NEW_PROFILE_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
